import { getModels } from "../models/index.js"
import {
  ROUTINE_STEP_CATEGORIES,
  STEP_ORDER_MAP,
  PRODUCT_TO_STEP_MAP,
  detectConflicts,
  getStepOrder,
  type RoutineStepCategory,
  type RoutineTime,
  type DetectedConflict,
} from "@skinory/core"

// ─── Types ───────────────────────────────────────────────────────────────────

export interface RoutineStepView {
  id: string
  stepOrder: number
  category: RoutineStepCategory
  productId: string | null
  productName: string
  brandName: string | null
  imageUrl: string | null
  matchScore: number | null
  usageInstruction: string | null
  timingNote: string | null
  inventoryItemId: string | null
}

export interface RoutineView {
  id: string
  name: string
  timeOfDay: RoutineTime
  isActive: boolean
  isAutoGenerated: boolean
  steps: RoutineStepView[]
  conflicts: DetectedConflict[]
}

export interface GenerateResult {
  morning: RoutineView
  evening: RoutineView
  conflicts: DetectedConflict[]
}

// ─── Errors ──────────────────────────────────────────────────────────────────

export class RoutineServiceError extends Error {
  constructor(
    public readonly code: string,
    public readonly status: number,
    message: string,
    public readonly details?: unknown,
  ) {
    super(message)
    this.name = "RoutineServiceError"
  }
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function inferStepCategory(product: any): RoutineStepCategory {
  const sub = (product.subcategory ?? "").toLowerCase().trim()
  if (sub && PRODUCT_TO_STEP_MAP[sub]) return PRODUCT_TO_STEP_MAP[sub]

  const form = (product.productForm ?? "").toLowerCase().trim()
  if (form && PRODUCT_TO_STEP_MAP[form]) return PRODUCT_TO_STEP_MAP[form]

  const name = (product.name ?? "").toLowerCase()
  for (const [keyword, category] of Object.entries(PRODUCT_TO_STEP_MAP)) {
    if (name.includes(keyword)) return category
  }

  return "moisturizing"
}

function computeMatchScore(product: any, skinProfile: any): number {
  if (!skinProfile) return 70

  let score = 75
  const desc = (product.description ?? "").toLowerCase()

  if (desc.includes("non-comedogenic")) score += 5
  if (desc.includes("fragrance-free") || desc.includes("fragrance free")) score += 5
  if (desc.includes("hypoallergenic")) score += 5
  if (desc.includes("dermatologist")) score += 3

  if (skinProfile.sensitivityLevel === "high") {
    if (desc.includes("gentle") || desc.includes("soothing") || desc.includes("calming")) score += 5
  }

  if (skinProfile.skinType === "oily" && desc.includes("oil-free")) score += 4
  if (skinProfile.skinType === "dry" && desc.includes("hydrating")) score += 4

  return Math.min(score, 99)
}

function buildIngredientSlugs(product: any): string[] {
  const ingredients = product.ingredients ?? product.Ingredients ?? []
  const slugs: string[] = []

  for (const ing of ingredients) {
    const name = ((ing.inciName ?? ing.displayName ?? "") as string).toLowerCase()
    if (name.includes("retinol") || name.includes("retinoid")) slugs.push("retinol")
    if (name.includes("glycolic") || name.includes("lactic")) slugs.push("aha")
    if (name.includes("salicylic")) slugs.push("bha")
    if (name.includes("ascorbic") || name.includes("vitamin c")) slugs.push("vitamin_c")
    if (name.includes("benzoyl peroxide")) slugs.push("benzoyl_peroxide")
    if (name.includes("niacinamide")) slugs.push("niacinamide")
  }

  return [...new Set(slugs)]
}

// ─── Public API ──────────────────────────────────────────────────────────────

export async function getRoutines(userId: string): Promise<RoutineView[]> {
  const { Routine, RoutineStep, Product, Brand, InventoryItem } = getModels()

  const routines = await Routine.findAll({
    where: { userId, isActive: true },
    include: [
      {
        model: RoutineStep,
        as: "steps",
        include: [
          {
            model: Product,
            as: "product",
            include: [{ model: Brand, as: "brand" }],
          },
          {
            model: InventoryItem,
            as: "inventoryItem",
          },
        ],
      },
    ],
    order: [
      ["timeOfDay", "ASC"],
      [{ model: RoutineStep, as: "steps" }, "stepOrder", "ASC"],
    ],
  })

  return routines.map((routine) => {
    const steps = ((routine as any).steps ?? []) as any[]

    const stepViews: RoutineStepView[] = steps.map((step: any) => {
      const product = step.product
      const brand = product?.brand
      const category = product ? inferStepCategory(product) : "moisturizing"

      return {
        id: step.id,
        stepOrder: step.stepOrder,
        category,
        productId: step.productId,
        productName: product?.name ?? "Unknown Product",
        brandName: brand?.name ?? null,
        imageUrl: product?.imageUrl ?? null,
        matchScore: null,
        usageInstruction: step.usageInstruction,
        timingNote: step.timingNote,
        inventoryItemId: step.inventoryItemId,
      }
    })

    const conflictItems = steps
      .filter((s: any) => s.product)
      .map((s: any) => ({
        productName: s.product.name,
        ingredientSlugs: buildIngredientSlugs(s.product),
      }))

    return {
      id: routine.id,
      name: routine.name,
      timeOfDay: routine.timeOfDay as RoutineTime,
      isActive: routine.isActive,
      isAutoGenerated: routine.isAutoGenerated,
      steps: stepViews,
      conflicts: detectConflicts(conflictItems),
    }
  })
}

export async function generateRoutine(userId: string): Promise<GenerateResult> {
  const { Routine, RoutineStep, Inventory, InventoryItem, Product, Brand, Ingredient, ProductIngredient, SkinProfile } = getModels()

  // Load user skin profile
  const skinProfile = await SkinProfile.findOne({ where: { userId } })

  // Load user inventory (inventory-first: only use products the user owns)
  const inventory = await Inventory.findOne({ where: { userId, isActive: true } })
  if (!inventory) {
    throw new RoutineServiceError(
      "NO_INVENTORY",
      404,
      "No active inventory found. Add products to your inventory first.",
    )
  }

  const inventoryItems = await InventoryItem.findAll({
    where: { inventoryId: inventory.id, status: "active" },
    include: [
      {
        model: Product,
        as: "product",
        where: { category: "skincare", isActive: true },
        include: [
          { model: Brand, as: "brand" },
          {
            model: Ingredient,
            as: "ingredients",
            through: { attributes: ["ingredientOrder"] },
          },
        ],
      },
    ],
  })

  if (!inventoryItems.length) {
    throw new RoutineServiceError(
      "NO_SKINCARE_PRODUCTS",
      404,
      "No skincare products in your inventory.",
    )
  }

  // Categorize products
  type CategorizedProduct = {
    inventoryItem: any
    product: any
    category: RoutineStepCategory
    matchScore: number
    ingredientSlugs: string[]
  }

  const categorized: CategorizedProduct[] = inventoryItems.map((item: any) => {
    const product = item.product
    return {
      inventoryItem: item,
      product,
      category: inferStepCategory(product),
      matchScore: computeMatchScore(product, skinProfile),
      ingredientSlugs: buildIngredientSlugs(product),
    }
  })

  // Detect global conflicts
  const allConflicts = detectConflicts(
    categorized.map((c) => ({
      productName: c.product.name,
      ingredientSlugs: c.ingredientSlugs,
    })),
  )

  // Group by category, pick best match per category (deterministic: sort by score desc, then name asc)
  const byCategory = new Map<RoutineStepCategory, CategorizedProduct[]>()
  for (const item of categorized) {
    const existing = byCategory.get(item.category) ?? []
    existing.push(item)
    byCategory.set(item.category, existing)
  }

  for (const [, items] of byCategory) {
    items.sort((a, b) => {
      if (b.matchScore !== a.matchScore) return b.matchScore - a.matchScore
      return a.product.name.localeCompare(b.product.name)
    })
  }

  // Deactivate existing auto-generated routines
  await Routine.update(
    { isActive: false },
    { where: { userId, isAutoGenerated: true, isActive: true } },
  )

  async function createRoutineForTime(timeOfDay: RoutineTime): Promise<RoutineView> {
    const stepOrder = STEP_ORDER_MAP[timeOfDay]
    const routineName = timeOfDay === "morning" ? "Morning Routine" : "Evening Routine"

    const routine = await Routine.create({
      userId,
      name: routineName,
      timeOfDay,
      isActive: true,
      isAutoGenerated: true,
    })

    const stepViews: RoutineStepView[] = []
    let order = 0

    for (const category of stepOrder) {
      const candidates = byCategory.get(category)
      if (!candidates?.length) continue

      const best = candidates[0]

      const step = await RoutineStep.create({
        routineId: routine.id,
        inventoryItemId: best.inventoryItem.id,
        productId: best.product.id,
        stepOrder: order,
        usageInstruction: null,
        timingNote: null,
      })

      stepViews.push({
        id: step.id,
        stepOrder: order,
        category,
        productId: best.product.id,
        productName: best.product.name,
        brandName: best.product.brand?.name ?? null,
        imageUrl: best.product.imageUrl ?? null,
        matchScore: best.matchScore,
        usageInstruction: null,
        timingNote: null,
        inventoryItemId: best.inventoryItem.id,
      })

      order++
    }

    // Filter conflicts relevant to this routine
    const routineProductNames = new Set(stepViews.map((s) => s.productName))
    const routineConflicts = allConflicts.filter(
      (c) => routineProductNames.has(c.productA) && routineProductNames.has(c.productB),
    )

    return {
      id: routine.id,
      name: routineName,
      timeOfDay,
      isActive: true,
      isAutoGenerated: true,
      steps: stepViews,
      conflicts: routineConflicts,
    }
  }

  const morning = await createRoutineForTime("morning")
  const evening = await createRoutineForTime("evening")

  return { morning, evening, conflicts: allConflicts }
}

export async function addStep(
  userId: string,
  routineId: string,
  productId: string,
  category: RoutineStepCategory,
): Promise<RoutineStepView> {
  const { Routine, RoutineStep, Product, Brand, Inventory, InventoryItem } = getModels()

  const routine = await Routine.findOne({ where: { id: routineId, userId } })
  if (!routine) {
    throw new RoutineServiceError("ROUTINE_NOT_FOUND", 404, "Routine not found")
  }

  const product = await Product.findByPk(productId, {
    include: [{ model: Brand, as: "brand" }],
  })
  if (!product) {
    throw new RoutineServiceError("PRODUCT_NOT_FOUND", 404, "Product not found")
  }

  // Check if product is in inventory
  const inventory = await Inventory.findOne({ where: { userId, isActive: true } })
  let inventoryItemId: string | null = null
  if (inventory) {
    const invItem = await InventoryItem.findOne({
      where: { inventoryId: inventory.id, productId, status: "active" },
    })
    inventoryItemId = invItem?.id ?? null
  }

  // Determine step order based on category position
  const rawTimeOfDay = routine.timeOfDay as string
  const effectiveTime: RoutineTime = rawTimeOfDay === "morning" || rawTimeOfDay === "evening"
    ? rawTimeOfDay
    : "morning"
  const targetOrder = getStepOrder(effectiveTime, category)

  // Shift existing steps if needed
  await RoutineStep.increment("stepOrder", {
    by: 1,
    where: {
      routineId: routine.id,
      stepOrder: { [Symbol.for("gte")]: targetOrder },
    },
  })

  const step = await RoutineStep.create({
    routineId: routine.id,
    inventoryItemId,
    productId,
    stepOrder: targetOrder,
    usageInstruction: null,
    timingNote: null,
  })

  return {
    id: step.id,
    stepOrder: targetOrder,
    category,
    productId,
    productName: product.name,
    brandName: (product as any).brand?.name ?? null,
    imageUrl: product.imageUrl ?? null,
    matchScore: null,
    usageInstruction: null,
    timingNote: null,
    inventoryItemId,
  }
}

export async function removeStep(userId: string, stepId: string): Promise<void> {
  const { Routine, RoutineStep } = getModels()

  const step = await RoutineStep.findByPk(stepId, {
    include: [{ model: Routine, as: "routine" }],
  })

  if (!step) {
    throw new RoutineServiceError("STEP_NOT_FOUND", 404, "Routine step not found")
  }

  const routine = (step as any).routine
  if (!routine || routine.userId !== userId) {
    throw new RoutineServiceError("STEP_NOT_FOUND", 404, "Routine step not found")
  }

  await step.destroy()
}

export function toPublicError(error: unknown): RoutineServiceError {
  if (error instanceof RoutineServiceError) return error
  console.error("Routine service error:", error)
  return new RoutineServiceError("INTERNAL_SERVER_ERROR", 500, "Unexpected server error")
}
