import {
  CreationOptional,
  DataTypes,
  ForeignKey,
  InferAttributes,
  InferCreationAttributes,
  Model,
  Sequelize,
} from "sequelize";
import { ROUTINE_TIME_OF_DAY } from "./db-types.js";
import type { DbModels } from "./index.ts";

export class Routine extends Model<InferAttributes<Routine>, InferCreationAttributes<Routine>> {
  declare id: CreationOptional<string>;
  declare userId: ForeignKey<string>;
  declare name: string;
  declare timeOfDay: (typeof ROUTINE_TIME_OF_DAY)[number];
  declare isActive: CreationOptional<boolean>;
  declare isAutoGenerated: CreationOptional<boolean>;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  static initModel(sequelize: Sequelize): typeof Routine {
    Routine.init(
      {
        id: { type: DataTypes.UUID, defaultValue: DataTypes.UUIDV4, primaryKey: true },
        userId: {
          type: DataTypes.UUID,
          allowNull: false,
          field: "user_id",
          references: { model: "users", key: "id" },
          onDelete: "CASCADE",
          onUpdate: "CASCADE",
        },
        name: {
          type: DataTypes.STRING,
          allowNull: false,
        },
        timeOfDay: {
          type: DataTypes.ENUM(...ROUTINE_TIME_OF_DAY),
          allowNull: false,
          field: "time_of_day",
          defaultValue: "anytime",
        },
        isActive: {
          type: DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: true,
          field: "is_active",
        },
        isAutoGenerated: {
          type: DataTypes.BOOLEAN,
          allowNull: false,
          defaultValue: true,
          field: "is_auto_generated",
        },
        createdAt: {
          type: DataTypes.DATE,
          allowNull: false,
          defaultValue: DataTypes.NOW,
          field: "created_at",
        },
        updatedAt: {
          type: DataTypes.DATE,
          allowNull: false,
          defaultValue: DataTypes.NOW,
          field: "updated_at",
        },
      },
      {
        sequelize,
        tableName: "routines",
        modelName: "Routine",
        freezeTableName: true,
        underscored: true,
        timestamps: true,
        indexes: [{ fields: ["user_id", "is_active"] }],
      }
    );

    return Routine;
  }

  static associate(models: DbModels): void {
    Routine.belongsTo(models.User, { foreignKey: "userId", as: "user" });
    Routine.hasMany(models.RoutineStep, { foreignKey: "routineId", as: "steps" });
  }
}
