import type { RoutineStepCategory, RoutineTime, DetectedConflict } from '@skinory/core'

const API_BASE = '/api/routine'

interface ApiOk<T> {
  ok: true
  data: T
}

interface ApiErr {
  ok: false
  error: { code: string; message: string; details?: unknown }
}

type ApiResult<T> = ApiOk<T> | ApiErr

function headers(userId: string): HeadersInit {
  return {
    'Content-Type': 'application/json',
    'x-user-id': userId,
  }
}

// ─── Types ───────────────────────────────────────────────────────────────────

export interface RoutineStepView {
  id: string
  stepOrder: number
  category: RoutineStepCategory
  productId: string | null
  productName: string
  brandName: string | null
  imageUrl: string | null
  matchScore: number | null
  usageInstruction: string | null
  timingNote: string | null
  inventoryItemId: string | null
}

export interface RoutineView {
  id: string
  name: string
  timeOfDay: RoutineTime
  isActive: boolean
  isAutoGenerated: boolean
  updatedAt: string
  steps: RoutineStepView[]
  conflicts: DetectedConflict[]
}

export interface GenerateResult {
  morning: RoutineView
  evening: RoutineView
  conflicts: DetectedConflict[]
}

// ─── API Functions ───────────────────────────────────────────────────────────

export async function getRoutines(userId: string): Promise<RoutineView[]> {
  const res = await fetch(API_BASE, {
    headers: headers(userId),
  })

  const json: ApiResult<RoutineView[]> = await res.json()
  if (!json.ok) throw new Error(json.error.message)
  return json.data
}

export async function generateRoutine(userId: string): Promise<GenerateResult> {
  const res = await fetch(`${API_BASE}/generate`, {
    method: 'POST',
    headers: headers(userId),
  })

  const json: ApiResult<GenerateResult> = await res.json()
  if (!json.ok) throw new Error(json.error.message)
  return json.data
}

export async function addStepToRoutine(
  userId: string,
  routineId: string,
  productId: string,
  category: RoutineStepCategory,
): Promise<RoutineStepView> {
  const res = await fetch(`${API_BASE}/steps`, {
    method: 'POST',
    headers: headers(userId),
    body: JSON.stringify({ routineId, productId, category }),
  })

  const json: ApiResult<RoutineStepView> = await res.json()
  if (!json.ok) throw new Error(json.error.message)
  return json.data
}

export async function removeRoutineStep(
  userId: string,
  stepId: string,
): Promise<void> {
  const res = await fetch(`${API_BASE}/steps/${stepId}`, {
    method: 'DELETE',
    headers: headers(userId),
  })

  const json: ApiResult<null> = await res.json()
  if (!json.ok) throw new Error(json.error.message)
}
